remote_theme: "mmistakes/minimal-mistakes@4.17.2"

# Plugins
plugins:
  - jekyll-include-cache

title: The social, the science and the humanities
description: >- # this means to ignore newlines until "baseurl:"
  Bridging three cultures of geographic information
  at GIScience Conference 2020
minimal_mistakes_skin: default
search: true

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-156564651-2
    anonymize_ip         : # true, false (default)

include:
  - _pages

author:
  name   : "Stef De Sabbata"
  avatar : "/assets/images/DeSabbata-Stef-headshot-small-square.jpg"
  bio    : "Lecturer in Quantitative Geography at the University of Leicester, Research Associate at the Oxford Internet Institute"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sdesabbata.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sdesabbata"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sdesabbata"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://https://twitter.com/maps4thought"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maps4thought"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
